#!/usr/bin/env python3
"""F3 v1 — minority report from an interpreter run (D22: dropping or conditioning another seed's accepted clause
must name the clause and its emitter; the emitter gains standing to force a re-hearing).

    python3 tools/minority_report.py result.json --emitters emitters.json [--out minority-report.md] [--inputs a,b]

Input: a g09-style result.json — `initial_spec`, `steps[]` with `given`, `outputs`, `current_spec` (at top level or
under `revision_through_u`, as tools/oracle-tests/g09-revision/run.py writes it). For every step whose
`current_spec` differs from the step before, the report gives: the update that arrived (the `given` value on the
stream routed to `u`, and `u`'s own value), the spec_diff classification per clause with its emitter and branch
condition, the outputs that flipped between that step and the next (with the inputs at both), and how each
later step's inputs stand against the branch conditions. It ends with "Standing": the emitters D22 entitles to a
re-hearing. Nothing here interprets Tau; every line is read from the record and cites its step index.
"""
from __future__ import annotations

import json, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from spec_diff import canon, diff, load_emitters, ParseError  # noqa: E402

_LIT = re.compile(r"^(?:(always|sometimes)\s+)?([A-Za-z_]\w*)\[t\]\s*(=|!=)\s*(0|1)$")


def _code(s: str, table: bool = False) -> str:
    """Inline code; `|` is escaped only inside a Markdown table cell."""
    return "`" + (str(s).replace("|", "\\|") if table else str(s)) + "`"


def _tc(s) -> str:
    return _code(s, table=True) if s else "-"


def _val(v: str) -> str:
    return str(v).strip().rstrip(".")


def _canon(s: str) -> str:
    try:
        return canon(s)
    except ParseError:
        return re.sub(r"\s+", " ", s).strip()


def literal_holds(lit: str, given: dict) -> str:
    """'satisfies' / 'violates' / '?' for a literal like `always i_x[t] = 0` against a step's given values (T./F. only)."""
    m = _LIT.match(lit.strip())
    if not m:
        return "?"
    _, name, op, const = m.groups()
    v = _val(given.get(name, ""))
    if v not in ("T", "F"):
        return "?"
    bit = "1" if v == "T" else "0"
    return "satisfies" if ((bit == const) == (op == "=")) else "violates"


def condition_holds(cond: str | None, given: dict) -> str:
    if not cond:
        return "-"
    verdicts = [literal_holds(p, given) for p in cond.split(" && ")]
    if "violates" in verdicts:
        return "violates"
    if "?" in verdicts:
        return "?"
    return "satisfies"


def find_update(step: dict, update_stream: str | None):
    """(input stream name, its value) carrying the update at this step: the given whose formula equals `u`'s value,
    else any given that is not a plain T./F. value."""
    u = _val(step.get("outputs", {}).get("u", "F"))
    given = step.get("given", {})
    if update_stream and update_stream in given:
        return update_stream, given[update_stream]
    if u not in ("T", "F", ""):
        cu = _canon(u)
        for k, v in given.items():
            if _val(v) not in ("T", "F") and _canon(v) == cu:
                return k, v
    for k, v in given.items():
        if _val(v) not in ("T", "F"):
            return k, v
    return None, None


def build(result: dict, emitters=None, inputs=None, update_stream=None, source="result.json", emitters_path=None) -> tuple[str, list]:
    r = result.get("revision_through_u", result)
    steps = r.get("steps", [])
    initial = r.get("initial_spec", "")
    inputs = set(inputs) if inputs else {k for s in steps for k in s.get("given", {})}
    em = load_emitters(emitters) if emitters else {}
    L, standing = [], []
    L.append(f"# Minority report — {source}")
    L.append("")
    L.append(f"Generated by `tools/minority_report.py` over `tools/spec_diff.py` v1. Source record: `{source}`"
             + (f" (ts {result['ts']})" if result.get("ts") else "") + (f", `{result['tau_version']}`" if result.get("tau_version") else "") + ".")
    L.append(f"Emitters map: `{emitters_path or '(none)'}`. Input streams: {', '.join(_code(i) for i in sorted(inputs))}.")
    for k in ("sat_seeds", "sat_update", "sat_conjunction"):
        if k in result:
            L.append(f"`{k}` = {result[k]} (record field).")
    if r.get("error"):
        L.append(f"Interpreter error recorded: `{r['error']}`.")
    L.append("")
    changed = []
    for i, st in enumerate(steps):
        prev = initial if i == 0 else steps[i - 1].get("current_spec", "")
        cur = st.get("current_spec", "")
        if _canon(prev) != _canon(cur):
            changed.append((i, prev, cur))
    if not changed:
        L.append(f"No step changed the running specification ({len(steps)} steps recorded). Nothing to report; no standing arises.")
    for i, prev, cur in changed:
        st = steps[i]
        k = st.get("k", i)
        L.append(f"## Step {k} — the running specification changed")
        L.append("")
        name, val = find_update(st, update_stream)
        u = _val(st.get("outputs", {}).get("u", ""))
        if name:
            L.append(f"- Update that arrived (step {k}, `given.{name}`): {_code(_val(val))}")
        else:
            L.append(f"- No update found among step {k}'s given values; `u` alone is reported.")
        L.append(f"- Proposed on `u` (step {k}, `outputs.u`): {_code(u)}")
        L.append(f"- Inputs at step {k}: " + ", ".join(f"{_code(n)} = {_code(_val(v))}" for n, v in st.get("given", {}).items() if n != name))
        L.append(f"- Spec before (step {k - 1 if i else 'initial'}): {_code(_canon(prev))}")
        L.append(f"- Spec after (step {k}): {_code(_canon(cur))}")
        L.append("")
        d = diff(prev, cur, emitters=em, inputs=inputs)
        L.append(f"### Clause classification (step {k}: before vs after)")
        L.append("")
        L.append("| clause | emitter | status | lives only if | branch condition |")
        L.append("|---|---|---|---|---|")
        for c in d["clauses"]:
            L.append(f"| {_tc(c['clause'])} | {c['emitter'] or 'null'} | {c['status']} | {_tc(c['lives_only_if'])} | {_tc(c['branch_condition'])} |")
            if c["status"] in ("dropped", "conditional"):
                standing.append({"step": k, **c})
        if d["added_detail"]:
            L.append("")
            L.append(f"Added at step {k}:")
            L.append("")
            for a in d["added_detail"]:
                cond = f" — lives only if {_code(a['lives_only_if'])}" if a.get("lives_only_if") else ""
                cond = cond or (f" — branch {_code(a['branch_condition'])}" if a.get("branch_condition") else "")
                L.append(f"- {_code(a['clause'])} ({a['status']}{cond})")
        if d["disjunctions"]:
            L.append("")
            for dj in d["disjunctions"]:
                L.append(f"Disjunction {dj['index']} in the spec after step {k} has {len(dj['branches'])} branches: "
                         + "; ".join(f"[{j}] {_code(b)}" for j, b in enumerate(dj["branches"])))
        L.append("")
        # observable consequence: outputs at step k (pre-revision spec in force) vs step k+1 (revised spec)
        L.append(f"### Observable consequence (step {k} → step {k + 1})")
        L.append("")
        if i + 1 < len(steps):
            nx = steps[i + 1]
            g0, g1 = st.get("given", {}), nx.get("given", {})
            o0, o1 = st.get("outputs", {}) or {}, nx.get("outputs", {}) or {}
            same = [n for n in g0 if n in g1 and _val(g0[n]) == _val(g1[n])]
            diffin = [n for n in set(g0) | set(g1) if _val(g0.get(n, "")) != _val(g1.get(n, ""))]
            L.append(f"- Inputs unchanged between step {k} and step {k + 1}: " + (", ".join(f"{_code(n)} = {_code(_val(g0[n]))}" for n in same) or "none"))
            L.append(f"- Inputs that differ: " + (", ".join(f"{_code(n)} {_code(_val(g0.get(n, '')))} → {_code(_val(g1.get(n, '')))}" for n in sorted(diffin)) or "none"))
            flips = [(n, _val(o0.get(n, "")), _val(o1.get(n, ""))) for n in sorted(set(o0) | set(o1)) if _val(o0.get(n, "")) != _val(o1.get(n, ""))]
            if flips:
                for n, a, b in flips:
                    L.append(f"- Output {_code(n)} flipped: step {k} {_code(a)} → step {k + 1} {_code(b)}")
            else:
                L.append(f"- No output differs between step {k} and step {k + 1}.")
        else:
            L.append(f"- Step {k} is the last recorded step; no later outputs to compare.")
        # later steps under this spec
        later = []
        for j in range(i + 1, len(steps)):
            if any(cj == j for cj, _, _ in changed):
                break
            later.append(steps[j])
        conds = sorted({c["lives_only_if"] for c in d["clauses"] if c.get("lives_only_if")})
        if later:
            L.append("")
            L.append(f"Steps run under the spec produced at step {k}. The last column(s) check the step's input against the "
                     f"branch literal pointwise (satisfies/violates at that step); whether the `always` branch is live is the interpreter's business, not read here:")
            L.append("")
            L.append("| step | inputs | outputs | " + " | ".join(f"input vs {_tc(c)}" for c in conds) + (" |" if conds else ""))
            L.append("|---|---|---|" + "---|" * len(conds))
            for s2 in later:
                gi = ", ".join(f"{n}={_val(v)}" for n, v in s2.get("given", {}).items())
                oi = ", ".join(f"{n}={_val(v)}" for n, v in (s2.get("outputs") or {}).items())
                row = f"| {s2.get('k')} | {_tc(gi)} | {_tc(oi)} |"
                row += "".join(f" {condition_holds(c, s2.get('given', {}))} |" for c in conds)
                L.append(row)
        L.append("")
    L.append("## Standing (D22)")
    L.append("")
    if not standing:
        L.append("No accepted clause was dropped or made conditional; no emitter gains standing.")
    else:
        by = {}
        for s in standing:
            by.setdefault(s["emitter"], []).append(s)
        for emitter, items in sorted(by.items(), key=lambda kv: (kv[0] is None, str(kv[0]))):
            if emitter is None:
                L.append("- Unattributed (emitter null): the following clauses need an emitter before standing can be assigned (D22 requires the emitter be named).")
            else:
                L.append(f"- `{emitter}` may force a re-hearing:")
            for s in items:
                cond = f"; lives only if {_code(s['lives_only_if'])}" if s.get("lives_only_if") else (f"; branch {_code(s['branch_condition'])}" if s.get("branch_condition") else "")
                L.append(f"  - step {s['step']}: {_code(s['clause'])} — {s['status']}{cond}")
    L.append("")
    return "\n".join(L), standing


def main():
    argv = sys.argv[1:]
    if not argv or argv[0].startswith("-"):
        print(__doc__); sys.exit(0)
    path = argv[0]
    opt = lambda f: argv[argv.index(f) + 1] if f in argv else None  # noqa: E731
    result = json.load(open(path))
    inputs = [s.strip() for s in opt("--inputs").split(",")] if opt("--inputs") else None
    md, _ = build(result, emitters=opt("--emitters"), inputs=inputs, update_stream=opt("--update-stream"),
                  source=os.path.relpath(path), emitters_path=opt("--emitters"))
    out = opt("--out")
    if out:
        open(out, "w").write(md)
        print(f"wrote {out}")
    else:
        print(md)


if __name__ == "__main__":
    main()
